### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by copywizard** [JDolven/Replacing-HF_LPT120A-in-a-millheat-heater#2]
Hello i have 2 questions

1: I have nearly everything working and installed the D1 mini into my Gen2 glass panel heater.
But when i try to change the temperature it does nothing.
My phone says that i set the device to for instance 20C but after 3 sec it just drops down again to 9 where it was.
The temperature on the display of the heater does also NOT change.
If i use the buttons on the heater it goes up and does report this temperature back to HA!

2: when compiling the binary to install it it manually it gives me a warning.

In file included from src/main.cpp:36:
src/mill.h: In member function 'virtual void MyCustomClimate::control(const esphome::climate::ClimateCall&)':
src/mill.h:58:16: warning: enumeration value 'CLIMATE_MODE_HEAT_COOL' not handled in switch [-Wswitch]
   58 |         switch (call.get_mode().value()) {
      |                ^
src/mill.h:58:16: warning: enumeration value 'CLIMATE_MODE_COOL' not handled in switch [-Wswitch]
src/mill.h:58:16: warning: enumeration value 'CLIMATE_MODE_FAN_ONLY' not handled in switch [-Wswitch]
src/mill.h:58:16: warning: enumeration value 'CLIMATE_MODE_DRY' not handled in switch [-Wswitch]
src/mill.h:58:16: warning: enumeration value 'CLIMATE_MODE_AUTO' not handled in switch [-Wswitch]

any idea what this can be?

**Comment by JDolven** [comment]
1.   What's the log output from the device in ESPHome? When changing the temperature from Home Assistant, does the target temperature change to 20°C and then back to 9°C in the log?

 2.   The warning is due to this part of the code not having a CASE for all the climate modes. I have the same warning when compiling. I'll try to sort it out.
`  void control(const ClimateCall &call) override {
    if (call.get_mode().has_value()) {

        switch (call.get_mode().value()) {
                case CLIMATE_MODE_OFF:
                  sendCmd(settPower, sizeof(settPower), 0x00);
                    break;
                case CLIMATE_MODE_HEAT:
                  sendCmd(settPower, sizeof(settPower), 0x01);
                    break;
        }`

**Comment by copywizard** [comment]
thanks for the quick reply!
I,am building a new binary as we speak i used visual code to see if there where any problems there was a problem with indents at the temperatures so maybe that's it give me 10 min to check it and i will try and see if i can get some mote out of the logs.

**Comment by copywizard** [comment]
these are some of the logs 

[19:15:56][D][climate:403]:   Current Temperature: 22.00°C
[19:15:56][D][climate:409]:   Target Temperature: 15.00°C
[19:15:56][D][climate:011]: 'Kitchen' - Setting
[19:15:56][D][climate:040]:   Target Temperature: 16.00
[19:15:56][D][climate:380]: 'Kitchen' - Sending state:
[19:15:56][D][climate:383]:   Mode: HEAT
[19:15:56][D][climate:403]:   Current Temperature: 22.00°C
[19:15:56][D][climate:409]:   Target Temperature: 16.00°C
[19:15:56][D][climate:380]: 'Kitchen' - Sending state:
[19:15:56][D][climate:383]:   Mode: HEAT
[19:15:56][D][climate:403]:   Current Temperature: 22.00°C
[19:15:56][D][climate:409]:   Target Temperature: 13.00°C
[19:15:56][D][climate:380]: 'Kitchen' - Sending state:
[19:15:56][D][climate:383]:   Mode: HEAT
[19:15:56][D][climate:403]:   Current Temperature: 22.00°C
[19:15:56][D][climate:409]:   Target Temperature: 13.00°C

**Comment by JDolven** [comment]
Can you change the mode to OFF from Home Assistant, or does it change back to HEAT?

**Comment by copywizard** [comment]
Yes changing it from off to heat and visa versa works

**Comment by copywizard** [comment]
Just to be sure you did not solder the reset pin to any pin on the D1 mini right? So of the 5 pins that where used by the old wifi chip you only used 4 correct?

**Comment by JDolven** [comment]
I only soldered 4 pins: GND, +3.3V, RX, and TX.
I'm having trouble reproducing the error.

I fixed the compile warning by adding "default:" to a switch case in mill.h.

**Comment by copywizard** [comment]
Ok thanks I will try and build the new binary when I get home and test it out I will also send over pictures of the installation.
But I think it's not at fault because I have wired it exactly as you did.
And everything works except that I cannot change the temperature using HA. I will keep you posted.

**Comment by copywizard** [comment]
Thanks for fixing the warnings looks alot cleaner

But even after these updates the problem persists i have no clue what this could be everything seems ok in HA but somehow it does not work?


![PXL_20231115_203932732](https://github.com/JDolven/Replacing-HF_LPT120A-in-a-millheat-heater/assets/20820085/dd7b85c5-3519-487c-a097-d37c6734a793)
![PXL_20231115_203941368](https://github.com/JDolven/Replacing-HF_LPT120A-in-a-millheat-heater/assets/20820085/0adbf316-ed03-4909-97bf-0e0bbd975442)
![PXL_20231115_204524535 MP](https://github.com/JDolven/Replacing-HF_LPT120A-in-a-millheat-heater/assets/20820085/b96028c9-852f-46a7-8883-522676614f2e)

**Comment by copywizard** [comment]
Ok did some quick testing and i removed the D1 mini and got a new D1 mini in using jumper wires so testing would be alot easier i also tried some test points on the back of the heater PCB with the same labeling and tested the connections they are all solid.
When i connect only the D1 mini to HA without hooking up any cables it works so the temp changes stick.
But once i connect all 4 cables it goes back to just jumping back to the original temp every time
![PXL_20231115_215928720](https://github.com/JDolven/Replacing-HF_LPT120A-in-a-millheat-heater/assets/20820085/779d2e88-be2e-4d73-832c-b2f24f8d4aed)
![PXL_20231115_215942387](https://github.com/JDolven/Replacing-HF_LPT120A-in-a-millheat-heater/assets/20820085/0efceaf3-dc6a-4f96-a098-136d1592b935)
.

**Comment by JDolven** [comment]
The wiring looks correct to me. It's strange; it seems like the heater is not receiving or is ignoring the set temperature from Home Assistant and is, in turn, sending the current set temperature, overwriting it in Home Assistant.

You can try commenting out the part of the code that reads from the heater and see if it sticks on Home Assistant and the heater.

`          if (receivedChars[6] != 0 ) {
          this->target_temperature= receivedChars[6];
          }`

Possibly, you have a different revision of the LCD board than mine, and it requires the last wire to be connected to a GPIO, as shown in https://github.com/trondsundt/MillHeat-ESPHome-NodeMCU. The GPIO is assigned in the YAML.

**Comment by copywizard** [comment]
Thanks for these tips I will try this tomorrow. And I will keep you posted

**Comment by NessK** [comment]
Hi,

I experience the same issue on a installation I did yesterday, I receive setpoint changes in HA, and can control heating On/Off from HA, but im unable to change the setpoints. When changing setpoints from HA it jump back to the previous setting.

Im following the progress of the suggestion in the previous post.

Thank you for the fantastic job that you have done here!

**Comment by JDolven** [comment]
It occurred to me that in the MillHeat-ESPHome-NodeMCU code, the temperature is written to position 7 in the array, whereas in my code, it's at position 8. I conducted a test and changed it to 7, but I was unable to set the target temperature. Could you please try changing the location where the set temperature is written?

Change the value 8 to 7. 
mill.h
`  if (arrayen[4] == 0x43) { // Temperatur
    arrayen[8] = kommando;
  }`

**Comment by NessK** [comment]
Hi,

Thanks for follwing up!

I changed line 140/141 in mill.h to the below and recompiled.
  if (arrayen[4] == 0x43) { // Temperatur
    arrayen[7] = kommando;

The result is the same, I am unable to set the temperature from HA, it jumps back to the original setpoint after a few seconds.

**Comment by JDolven** [comment]
I realized there was more that needed to be changed. Now, the set temperature part is identical to MillHeat-ESPHome-NodeMCU, and it's working.

**Comment by NessK** [comment]
I changed this typo from 43 to 46 and it works like a charm! Again, thank for you excellent work and commitment! God helg!!
```
  if (arrayen[4] == 0x46) { // Temperatur (OLD  0x43)
    arrayen[7] = kommando;
  }
```

**Comment by copywizard** [comment]
I will try the same as soon as possible and will let you know if this has worked for so far super thanks for the quick replies

**Comment by copywizard** [comment]
hmmm i changed the same thing but it still is not working for me am i doing something wrong?

`/*--- Funksjon for summering av kontrollbyte ---*/
unsigned char checksum(char *buf, int len) {

  unsigned char chk = 0;
  for ( ; len != 0; len--) {
    chk += *buf++;
  }
  return chk;
}
/* Seriedata ut til mill mikrokontroller ---*/
void sendCmd(char* arrayen, int len, int kommando) {

  if (arrayen[4] == 0x46) { // Temperatur
    arrayen[7] = kommando;
  }
  if (arrayen[4] == 0x47) { // Power av/på
    arrayen[5] = kommando;
    arrayen[len] = (byte)0x00;  // Padding..
  }
  char crc = checksum(arrayen, len + 1);
  Serial.write((byte)0x5A); // Startbyte
  for (int i = 0; i < len + 1; i++) { // Beskjed
    Serial.write((byte)arrayen[i]);
  }
  Serial.write((byte)crc); // Kontrollbyte
  Serial.write((byte)0x5B); // Stoppbyte
}
};`

**Comment by NessK** [comment]
There are more updates to mill.h. Copy the entire mill.h from this repository and update with the typo from my previous post.

**Comment by copywizard** [comment]
You legends! thanks very much it is working now
